name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List directory contents (debug)
        run: ls -la

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Run frontend tests
        run: cd frontend && npm test -- --coverage

      - name: Run backend tests
        run: cd backend && npm test -- --coverage

      - name: SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v1.5
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=manas-56
            -Dsonar.sources=./frontend/src,./backend/src
            -Dsonar.tests=./frontend/__tests__,./backend/__tests__
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
            -Dsonar.host.url=https
